---
- name: Configure pluto
  hosts: pluto
  remote_user: root

  tasks:
    - name : Ensure that amd gpu can be overclocked
      ansible.builtin.copy:
        src: cmdline.d/overclock-amdgpu.conf
        dest: /etc/cmdline.d
        owner: root
        group: root
        mode: u+rw,g=r,o=r
      register: cmdline
    - name: Regenerate kernel UKI
      ansible.builtin.command: mkinitcpio -p linux
      when: cmdline.changed
    - name: Ensure fan2go configuration directory exists
      ansible.builtin.file:
        path: /etc/fan2go
        state: directory
        mode: u+rw,g=r,o=r
    - name: Copy fan2go config
      ansible.builtin.copy:
        src: fan2go/fan2go.yaml
        dest: /etc/fan2go/fan2go.yaml
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Ensure that fan2go service is enabled and started
      ansible.builtin.systemd_service:
        name: fan2go
        state: started
        enabled: true
    - name: Ensure that kernel module for motherboard sensors are loaded on boot
      ansible.builtin.copy:
        src: modules-load.d/motherboard-sensors.conf
        dest: /etc/modules-load.d/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
