---
- name: Configure pluto
  hosts: pluto
  remote_user: root

  tasks:
    - name: Set kernel commandline
      ansible.builtin.copy:
        src: etc/kernel/
        dest: /etc/kernel/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Copy UKI creation (#1)
      ansible.builtin.copy:
        src: etc/kernel/postinst.d/
        dest: /etc/kernel/postinst.d/
        owner: root
        group: root
        mode: u+rwx,g=r,o=r
    - name: Copy UKI creation (#2)
      ansible.builtin.copy:
        src: etc/initramfs/post-update.d/
        dest: /etc/initramfs/post-update.d/
        owner: root
        group: root
        mode: u+rwx,g=r,o=r
    - name: Configure gpu overclock
      ansible.builtin.copy:
        src: etc/tmpfiles.d/gpu-undervolt.conf
        dest: /etc/tmpfiles.d/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
      register: gpu_undervolt
    - name: Apply gpu overclock
      ansible.builtin.command: systemd-tmpfiles --create /etc/tmpfiles.d/gpu-undervolt.conf
      when: gpu_undervolt.changed
    - name: Configure sddm
      ansible.builtin.copy:
        src: etc/sddm.conf.d/
        dest: /etc/sddm.conf.d/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Ensure fan2go configuration directory exists
      ansible.builtin.file:
        path: /etc/fan2go
        state: directory
        mode: u+rw,g=r,o=r
    - name: Copy fan2go config
      ansible.builtin.copy:
        src: etc/fan2go/fan2go.yaml
        dest: /etc/fan2go/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Copy fan2go service
      ansible.builtin.copy:
        src: etc/systemd/system/
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Configure openssh
      ansible.builtin.copy:
        src: etc/ssh/sshd_config.d/
        dest: /etc/ssh/sshd_config.d/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
      register: sshd_config
    - name: Restart SSH service if config changed
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      when: sshd_config.changed
    - name: Install fan2go
      ansible.builtin.copy:
        src: usr/bin/
        dest: /usr/bin/
        owner: root
        group: root
        mode: u+rwx,g=r,o=r
    - name: Ensure that fan2go service is enabled and started
      ansible.builtin.systemd_service:
        name: fan2go
        state: started
        enabled: true
    - name: Ensure that kernel module for motherboard sensors are loaded on boot
      ansible.builtin.copy:
        src: etc/modules-load.d/motherboard-sensors.conf
        dest: /etc/modules-load.d/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Add the user 'maik'
      ansible.builtin.user:
        name: maik
        uid: 1000
        group: sudo
    - name: Setup debian apt list
      ansible.builtin.copy:
        src: etc/apt/sources.list.d/
        dest: /etc/apt/sources.list.d/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Setup debian apt keyrings
      ansible.builtin.copy:
        src: etc/apt/keyrings/
        dest: /etc/apt/keyrings/
        owner: root
        group: root
        mode: u+rw,g=r,o=r
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent
    - name: Update APT cache if not too recent
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Ensure that expected packages are present
      ansible.builtin.apt:
        name:
          - akonadi-backend-sqlite
          - ansible-core
          - apt-transport-https
          - aspell-de
          - bash-completion
          - binutils
          - firefox-esr
          - firefox-esr-l10n-de
          - gawk
          - gwenview
          - merkuro
          - fonts-inter
          - fonts-inter-variable
          - kde-plasma-desktop
          - kdepim-addons
          - kmail
          - konsole
          - libpam-fscrypt
          - neochat
          - okular
          - plymouth
          - plymouth-themes
          - sudo
          - syncthing
          - systemd-boot-efi
          - tokodon
        state: present
    - name: Debloat install
      ansible.builtin.apt:
        name:
          - kde-style-oxygen-qt5
          - kde-style-oxygen-qt6
          - sddm-theme-debian-breeze
        state: absent
      ignore_errors: true
