#!/bin/bash
set -e

/usr/lib/systemd/ukify build \
    --linux="$2" \
    --initrd="/boot/initrd.img-$1" \
    --cmdline="@/etc/kernel/cmdline" \
    --secureboot-private-key=/etc/kernel/secure-boot-private-key.pem \
    --secureboot-certificate=/etc/kernel/secure-boot-certificate.pem \
    --output="/boot/efi/debian.efi"
